version: '2'
services:
  web:
    build: web
    command: ./node_modules/.bin/nodemon server.js
    depends_on: [mongo, memcached]
    environment:
      - ENV=development
      - MEMCACHED_HOST=memcached
      - 'MONGO_URL=mongodb://mongo:27017/electricity'
    ports: ['8000:8000']
    volumes:
      - './web/app:/home/app'
      - './web/index.html:/home/index.html'
      - './web/package.json:/home/package.json'
      - './web/public:/home/public'
      - './web/server.js:/home/server.js'
      - './web/webpack.config.js:/home/webpack.config.js'
  feeder:
    build: feeder
    depends_on: [mongo]
    env_file: ./secrets.env
    environment:
      - ENV=development
      - MEMCACHED_HOST=memcached
      - 'MONGO_URL=mongodb://mongo:27017/electricity'
    volumes:
      - './feeder/feeder.py:/home/feeder.py'
      - './feeder/parsers:/home/parsers'
  memcached:
    image: memcached
  mongo:
    image: mongo
    volumes: ['./mongodata/:/data/db']
