version: '2'
services:
  web:
    extends:
      file: common.yml
      service: web
    ports: ["8000:8000"]
    volumes: ['.:/home/']
    environment: [ENV=development]
    depends_on: [mongo]
  mongo:
    image: mongo
