version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/home/
    depends_on:
     - mongo
    env_file:
     - "~/Google\ Drive/dotfiles/mailgun.env"
  mongo:
    image: mongo
