version: '2'
services:
  api:
    build: api
    command: ./node_modules/.bin/nodemon server.js
    depends_on: [mongo]
    environment: [ENV=development, 'MONGO_URL=mongodb://mongo:27017/electricity']
    ports: ['8000:8000']
    volumes:
      - './api/static:/home/static'
      - './api/server.js:/home/server.js'
      - './api/data:/home/data'
  feeder:
    build: feeder
    depends_on: [mongo]
    environment: [ENV=development, 'MONGO_URL=mongodb://mongo:27017/electricity']
    volumes:
      - './api/data:/home/data'
  mongo:
    image: mongo
    volumes: ['./mongodata/:/data/db']
