version: '2'
services:
  web:
    extends:
      file: common.yml
      service: web
    ports: ['8000:8000']
    volumes:
      - './public:/home/public'
      - './backend:/home/backend'
      - './server.py:/home/server.py'
    environment: [ENV=development, 'MONGO_URL=mongodb://mongo:27017']
    depends_on: [mongo]
  mongo:
    image: mongo
    volumes: ['./mongodata/:/data/db']
