version: '2'
services:
  web:
    extends:
      file: common.yml
      service: web
    ports: ["8000:8000"]
    environment: [ENV=production]
    env_file: ./mailgun.env
    depends_on: [mongo]
    restart: on-failure
  mongo:
    image: mongo
    restart: on-failure
    volumes: ['/home/shared/electricitymap/data:/data/db']
